  File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
  File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
  File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
Not Found: /api_login_post
[30/Nov/2019 08:24:59] "POST /api_login_post HTTP/1.1" 404 3154
Performing system checks...

System check identified no issues (0 silenced).
November 30, 2019 - 08:24:53
Django version 2.0.3, using settings 'apimadetest.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[30/Nov/2019 08:25:16] "POST /api_login_post/ HTTP/1.1" 200 40
Not Found: /api_login_post
[30/Nov/2019 08:25:29] "POST /api_login_post HTTP/1.1" 404 3154
Not Found: /api_login_post
[30/Nov/2019 08:25:58] "POST /api_login_post HTTP/1.1" 404 3154
[30/Nov/2019 08:27:44] "POST /api_login_post/ HTTP/1.1" 200 40
Not Found: /api_login_post
[30/Nov/2019 08:28:58] "POST /api_login_post HTTP/1.1" 404 3154
[30/Nov/2019 08:29:07] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
Not Found: /api_login_post
[30/Nov/2019 08:29:07] "POST /api_login_post HTTP/1.1" 404 3154
[30/Nov/2019 08:29:16] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
Not Found: /api_login_post
[30/Nov/2019 08:29:16] "POST /api_login_post HTTP/1.1" 404 3154
[30/Nov/2019 08:29:34] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 08:29:35] "POST /api_login_post/ HTTP/1.1" 200 40
[30/Nov/2019 08:45:16] "POST /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 405 41
[30/Nov/2019 08:47:21] "POST /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 405 41
[30/Nov/2019 08:48:06] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 08:50:14] "POST /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 405 41
[30/Nov/2019 08:51:21] "GET /api_login_get?username=luoshiling&password=admin12345&user=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 08:52:02] "GET /api_login_get?username=luoshiling&password=admin12345&user=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 08:52:19] "GET /api_login_get?username=luoshiling&password=admin12345&user=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 08:52:27] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 08:53:34] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 08:55:14] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 08:55:16] "GET /api_login_get?username=luoshiling&password=admin12345&user=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 08:59:27] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 08:59:50] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 09:00:59] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 09:01:20] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 09:01:25] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 09:02:12] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 09:08:39] "POST /api_login_post/ HTTP/1.1" 200 40
[30/Nov/2019 09:10:18] "POST /api_login_post/ HTTP/1.1" 200 40
Internal Server Error: /api_add_order/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/luoshiling/apimadetest/apitest/views.py", line 236, in create_order
    data = json.loads(request.body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[30/Nov/2019 09:25:33] "POST /api_add_order/ HTTP/1.1" 500 15239
[30/Nov/2019 09:27:38] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
Internal Server Error: /api_add_order/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/luoshiling/apimadetest/apitest/views.py", line 236, in create_order
    data = json.loads(request.body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[30/Nov/2019 09:28:30] "POST /api_add_order/ HTTP/1.1" 500 15239
Internal Server Error: /api_add_order/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/luoshiling/apimadetest/apitest/views.py", line 251, in create_order
    return Response({"status_code": 400, "msg": luid + "不存在"})
TypeError: unsupported operand type(s) for +: 'int' and 'str'
[30/Nov/2019 09:29:42] "POST /api_add_order/ HTTP/1.1" 500 14565
[30/Nov/2019 09:30:14] "POST /api_add_order/ HTTP/1.1" 200 46
[30/Nov/2019 09:30:30] "POST /api_add_order/ HTTP/1.1" 200 46
Internal Server Error: /api_add_order/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/luoshiling/apimadetest/apitest/views.py", line 236, in create_order
    data = json.loads(request.body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[30/Nov/2019 09:31:29] "POST /api_add_order/ HTTP/1.1" 500 15239
Internal Server Error: /api_add_order/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/luoshiling/apimadetest/apitest/views.py", line 236, in create_order
    data = json.loads(request.body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[30/Nov/2019 09:31:43] "POST /api_add_order/ HTTP/1.1" 500 15239
[30/Nov/2019 09:31:54] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
[30/Nov/2019 09:32:11] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
Internal Server Error: /api_add_order/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/luoshiling/apimadetest/apitest/views.py", line 236, in create_order
    data = json.loads(request.body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[30/Nov/2019 09:33:58] "POST /api_add_order/ HTTP/1.1" 500 15239
[30/Nov/2019 09:34:37] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
Internal Server Error: /api_add_order/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/luoshiling/apimadetest/apitest/views.py", line 236, in create_order
    data = json.loads(request.body)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[30/Nov/2019 09:38:28] "POST /api_add_order/ HTTP/1.1" 500 15239
[30/Nov/2019 09:39:27] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
[30/Nov/2019 09:39:48] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
[30/Nov/2019 09:40:09] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
[30/Nov/2019 09:40:17] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
[30/Nov/2019 09:40:30] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
[30/Nov/2019 09:41:50] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
[30/Nov/2019 09:43:40] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
[30/Nov/2019 09:45:52] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
[30/Nov/2019 09:46:06] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 56
Performing system checks...

System check identified no issues (0 silenced).
November 30, 2019 - 08:25:09
Django version 2.0.3, using settings 'apimadetest.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
November 30, 2019 - 09:46:40
Django version 2.0.3, using settings 'apimadetest.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[30/Nov/2019 09:47:53] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 46
[30/Nov/2019 09:48:21] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 46
[30/Nov/2019 09:48:40] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 46
[30/Nov/2019 10:03:08] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 46
[30/Nov/2019 10:09:08] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 46
[30/Nov/2019 10:09:08] "POST /api_add_order/ HTTP/1.1" 200 46
[30/Nov/2019 10:10:07] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 46
[30/Nov/2019 10:10:07] "POST /api_add_order/ HTTP/1.1" 200 46
[30/Nov/2019 10:10:40] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 46
[30/Nov/2019 10:10:40] "POST /api_add_order/ HTTP/1.1" 200 46
[30/Nov/2019 10:10:41] "POST /api_login_post/ HTTP/1.1" 200 40
[30/Nov/2019 10:10:41] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 10:10:41] "POST /api_login_post/ HTTP/1.1" 200 40
[30/Nov/2019 10:13:49] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 46
[30/Nov/2019 10:13:49] "POST /api_add_order/ HTTP/1.1" 200 46
[30/Nov/2019 10:13:50] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 10:13:50] "POST /api_login_post/ HTTP/1.1" 200 40
[30/Nov/2019 10:13:54] "POST /api_add_lodgeinfo/ HTTP/1.1" 200 46
[30/Nov/2019 10:13:54] "POST /api_add_order/ HTTP/1.1" 200 46
[30/Nov/2019 10:13:54] "GET /api_login_get?username=luoshiling&password=admin12345 HTTP/1.1" 200 40
[30/Nov/2019 10:13:54] "POST /api_login_post/ HTTP/1.1" 200 40
